export const MAX_SITES_PER_USER = 25;
export const MAX_MONITORS_PER_SITE = 5;
export const MAX_INTEGRATIONS_PER_USER = 10;

export const DEFAULT_RATE_LIMIT_RUNS_PER_DAY = 100;
export const DEFAULT_RATE_LIMIT_SCHEDULED_RUNS_PER_DAY = 100;
